version: '3.8'
services:
  ocr-receipt:
    container_name: ocr_receipt
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - ocr-receipt
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
